name: Update Rules
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Download Rules
        continue-on-error: true
        run: |
          python ./data/python/dl.py
          
      - name: Merge Rules
        run: |
          python ./data/python/merge.py

      - name: Update Title&ReadMe
        run: |
          python ./data/python/title.py
          python ./data/python/clean-readme.py

      - name: Commit and Push changes
        run: |
          git init
          git config --global user.name "execute-darker"
          git config --global user.email "956853745@qq.com"
          git add --all
          git branch -m main
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S') (UTC+8)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/execute-darker/darker_adblock.git HEAD:main          

      - name: Delete workflow runs 
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
